### ISSUE TITLE
🎩 Down the Rabbit Hole You Go 🐇# - Quest 1 hyperlink broken.

### ISSUE THREAD

**Issue by Hiturunk** [MetaFam/metagame-wiki#121]
On the wiki here: https://wiki.metagame.wtf/docs/enter-metagame/how-to-become-a-player
A new user, discovering Metagame, gets their first quest:

1."Read WTF is MetaGame [hyperlink to https://wiki.metagame.wtf/docs/handbook/wtf-is-metagame],
2. subscribe to the "Realizing The MetaGame" newsletter.
3. & Introduce yourself on the forums."

Quest 1, step 1's hyperlink is broken, it returns a 404 from the HTTP request.

**Comment by Hiturunk** [comment]
Okay, upon further investigation, the hyperlink to step 1 of quest 1 needs to reference: 
"https://wiki.metagame.wtf/docs/wtf-is-metagame/wtf-is-metagame"

Not, as it currently does: 

"https://wiki.metagame.wtf/docs/handbook/wtf-is-metagame"

**Comment by peth-yursick** [comment]
Thank you sir! Closing this as it seems fixed in your PR :)
