### ISSUE TITLE
GUI editor not working

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#126]
I tried using the new editor but I couldn't submit.
This is what it gave:
Failed to persist entry: API_ERROR: Not Found

**Comment by luxumbra** [comment]
Does the whitelist for the Netlify api need to be updated after the move to Vercel? @hammadj @peth-yursick

**Comment by luxumbra** [comment]
Have either of you used Sanity.io? It's a really nice headless cms.

**Comment by Baconaetor** [comment]
@peth-yursick is this still an issue or can we close it?

**Comment by peth-yursick** [comment]
> 
> 
> @peth-yursick is this still an issue or can we close it?

Closing, thank you
