### ISSUE TITLE
Design Tweaks

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#128]
We'll soon be integrating the wiki under MyMeta and its navigation bar. Means we need to change a bunch of things about the wiki to make it match MyMeta' slickness.

Things that need to change:
- The color scheme of the wiki should match that of MyMeta
     - 1b0d2a for background
     - 261942 for sidebar
     - 392373 for mouse hover highlight
     - a5b9f6 for text
     - b72886 for explore button
     - 5a32e6 for "next page" frame
     - use the MyMeta [font](https://fonts.google.com/specimen/IBM+Plex+Sans?sidebar.open=true&selection.family=IBM+Plex+Sans)
- Once colors are different, we can get rid of the ugly white line separating the sidebar & text area.
- I think we should completely get rid of the top navigation bar, because MyMeta' nav bar will come above it. And for the new people we want them to go through one of three paths or click explore, not click straight to "join raid" and get confused. We also don't need the "light mode/dark mode" switch, just keep it dark 🐙
- Up for discussion, but I think we should also get rid of the footer section. The goal of the landing page wiki is to get visitors to explore it as a story not click around and get distracted from the storyline. All the links available down there and more, are available in the "Signpost" at the right step of player's journey through the wiki.
- Once we get rid of nav bar & footer, make it so that "metagame wiki", the headline & "players, guilds & patrons" appear mid-screen rather than top (leaving the bottom empty looking ugly).

Where to change them? I think [here](https://github.com/MetaFam/metagame-wiki/blob/master/src/css/custom.css).

**Comment by manolingam** [comment]
Working on this issue.

**Comment by peth-yursick** [comment]
> 
> 
> Working on this issue.

Hey, I see you've removed all the links from the top navigation bar, but you haven't actually removed the bar itself.
Its noticeable because there's a black line separating the main area and the nav bar, and the navbar is of a slightly different color.. If you only left it because of the search function, don't worry, we can get rid of that too.

**Comment by manolingam** [comment]
Yeah, because of search function Peth.

**Comment by luxumbra** [comment]
I'll jump on this this evening.

**Comment by peth-yursick** [comment]
Thank you guys!
