### ISSUE TITLE
Moar Design Tweaks

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#134]
Ok, there's 1 more issue and 2 more improvements possible.

Issue:
For some reason, when opening the "for players", "for guilds" & "for patrons", the whole sidebar moves upwards and leaves this gap in the bottom 
![image](https://user-images.githubusercontent.com/55857222/95456197-4515ab80-096f-11eb-9e2a-2ec11962a027.png)
For some reason it only happens with those 3 pages.

Improvement 1:
Can we make the sidebar ~30% wider so that some of the page titles don't break into new lines?

Improvement 2:
Can we make the whole sidebar round-edged (like on the profiles) & floating about halfway between left edge of the screen and the text in the middle?

Here's what the end-result would look like:
![image](https://user-images.githubusercontent.com/55857222/95459158-890aaf80-0973-11eb-8bd2-de3188c74447.png)
(made the container width & rounded exactly the same as on MyMeta https://web-39me.onrender.com/player/peth-yursick)
Also added some drop-shadow for the effect as a mini-sidequest

**Comment by luxumbra** [comment]
I'll grab this if no-one else is.

**Comment by luxumbra** [comment]
I've done the style updates for this but am going to need to do some responsive tweaks.
![image](https://user-images.githubusercontent.com/780350/95531236-f3553b80-09d7-11eb-9d28-cc17a47638bb.png)

**Comment by peth-yursick** [comment]
Right.. The sidebar container should probably be expanding and collapsing along with the text dropdown expanding & collapsing, always leaving the same sized margins on top & bottom as on left & right.

**Comment by peth-yursick** [comment]
I merged your PR @luxumbra because I think the XP is currently still mostly based around PRs vs impact and I thought you already did enough to deserve XP without further changes.

But, I do think there are still 3 more things to be done to make it perrrfect 😋

1. If you can bring back the text to the middle of the screen (sorry again for that misleading screenshot 😬)
2. Make the same size margin above the text as it is on the sides
![image](https://user-images.githubusercontent.com/55857222/95649408-9ba0f800-0add-11eb-84fd-76dbf359a0ab.png)
3. Have the container start small when all categories are collapsed, and have it expand and collapse dynamically as the categories are expanded & collapsed rather than stay the same the whole time only adding the scrolling bar. (imo rather expand the whole page and scroll the whole page than have the scroll bar on the sidebar)

**Comment by luxumbra** [comment]
Sure, I'll get those changes done at some point today. Good point re: the scrolling sidebar. 

Thanks for approving the PR & XP man. :grin:

**Comment by luxumbra** [comment]
@peth-yursick there's an approved PR for the rest of the bits in this issue plus some other bits resulting from Hammads review. :+1:
