### ISSUE TITLE
blank leaderboard showing on the leaderboard app drawer page

### ISSUE THREAD

**Issue by St4rgarden** [MetaFam/metagame-wiki#191]
So I am getting a blank leaderboard on this page right here -> https://wiki.metagame.wtf/docs/enter-metagame/leaderboard I am on High Sierra 10.13.6 and Chrome 86.0.4240.198 (Official Build) (x86_64)

**Comment by IxaBrjnko** [comment]
This seems to be an issue with the redirect... not sure if we should use sandboxing or 'dangerouslySetInnerHTML' to resolve, although the target is clearly trustable...

**Comment by luxumbra** [comment]
Is this not something to do with the SSL cert being invalid on xp.metagame.wtf?

**Comment by luxumbra** [comment]
This seems to be sorted now, so closing the issue. If it crops up again, fee free to open again.
