### ISSUE TITLE
Dead link to /home on /docs/how-does-it-work/phases-of-metagame page.

### ISSUE THREAD

**Issue by metaverde** [MetaFam/metagame-wiki#231]
Under "My Meta" [here](https://wiki.metagame.wtf/docs/how-does-it-work/phases-of-metagame) the  [https://wiki.metagame.wtf/home](https://wiki.metagame.wtf/home) link goes to "Page not found".

**Comment by metaverde** [comment]
I feel like this sentence under "MetaVille" should have a link in it?

> You can read a longer post about it here.

**Comment by metaverde** [comment]
Did this article happen?
We should link it if so.

> More in the Minimum Viable Stack article soon.

**Comment by luxumbra** [comment]
Thanks for these @metaverde. Did you want to tend to the issues or shall I seek a curious octo?

**Comment by peth-yursick** [comment]
> Under "My Meta" [here](https://wiki.metagame.wtf/docs/how-does-it-work/phases-of-metagame) the https://wiki.metagame.wtf/home link goes to "Page not found".


Damn, that should have been https://wiki.metagame.wtf/docs/home lol,
its been broken for who knows how many months now 🤣

> Did this article happen?
> We should link it if so.
> 
> > More in the Minimum Viable Stack article soon.

Yes! That would be this: https://wiki.metagame.wtf/docs/Guilding/metasys



> 
> 
> I feel like this sentence under "MetaVille" should have a link in it?
> 
> > You can read a longer post about it here.

Definitely, that would be here: https://forum.metagame.wtf/t/metaville/225

**Comment by Baconaetor** [comment]
There's another link missing. "To see the full post on MyMeta Profiles, go here."
Can't find that page at the moment though, I know I saw it somewhere. . . 🧐

**Comment by luxumbra** [comment]
> I know I saw it somewhere. . .
I know the feeling. Good luck. 😅

**Comment by jonathanprozzi** [comment]
I saw that too -- I wasn't sure what it should link to. I looked through the docs but wasn't sure what it could be.

**Comment by Baconaetor** [comment]
@peth-yursick Can you enlighten us as to where the page for the details on MyMeta Profiles is? Or has it not been created yet?

I think I found the page I was thinking of, but it ended up just being a newsletter article talking about future plans.

**Comment by luxumbra** [comment]
fixed in #243
