### ISSUE TITLE
Number of Seeds required for Patrons needs to be changed from 5 to 6. 

### ISSUE THREAD

**Issue by Baconaetor** [MetaFam/metagame-wiki#239]
8 pSEEDs are required to become a Patron. Originally 5 planted seeds was enough and so the docs reference that number. It was recently found though that planting 5 seeds can result in less than 8 pSEEDs, so the number is being changed to 6. @peth-yursick changed the number in the notion document for the Patron Path, but it still reads as 5 elsewhere. 

The discord conversation where this is discussed can be found here: 
https://discord.com/channels/629411177947987986/713513935789097102/850057867927093328

**Comment by Baconaetor** [comment]
PR #238 will resolve this issue for the "Join MetaGame" page on the wiki here:
https://wiki.metagame.wtf/docs/enter-metagame/join-metagame#join-as-a-patron

Does anyone know if this info is recorded, and needs to be changed, anywhere else?

**Comment by luxumbra** [comment]
The info is probably in newsletters and other places that can't be updated now but I know there's some pinned messages in discord channels (metasquare & ask-anything for example) that mention it.

**Comment by luxumbra** [comment]
Thanks for sorting this. PR merged.
