### ISSUE TITLE
Have Patrons Pool WETH Instead of Buying Seeds

### ISSUE THREAD

**Issue by Baconaetor** [MetaFam/metagame-wiki#242]
Per Discord conversation here:
https://discord.com/channels/629411177947987986/783432928804732928/851925062801162290
We've decided to have Patrons add WETH directly to the pSeed Balancer pool, instead of buying seeds first. So we need to:

- [x]     Calcuate a recommended WETH amount
- [ ]     Update all documentation

**Comment by Baconaetor** [comment]
Recommended WETH amount is 0.11 at time of writing.

**Comment by Baconaetor** [comment]
We saw a mention to the old old method recently (5 Seeds!), and we haven't been able to trace the source. Pretty sure it was an old newsletter though, which is fine.

**Comment by luxumbra** [comment]
> We saw a mention to the old old method recently (5 Seeds!), and we haven't been able to trace the source. Pretty sure it was an old newsletter though, which is fine.

In that case, I'll close this. Thanks @Baconaetor
