### ISSUE TITLE
Feedback on Eth Coaching Playbook

### ISSUE THREAD

**Issue by plasmacorral** [MetaFam/metagame-wiki#248]
@chair28980  in reference to playbook: https://wiki.metagame.wtf/docs/playbooks/how-to-coach-eth

Somewhere in here we should spell out for the coach and student/new user:  

A Low/slow gas transaction/event can inhibit the ability to complete subsequent transactions.   It can ultimately cost more gas in the end to have to cancel a slow transaction to facilitate a subsequent transaction that has more time sensitivity.  When gauging how patient one can be with a specific transaction, they must think of what they want to do with the address in the near future as well as how patient they can be on the activity or transaction immediately at hand.

Also, This would be a great document to also introduce ethgasstation.info

I couldn't seem to find a way to comment/suggest/collaborate on this particular wiki article.  If that requires a separate issue report just let me know.
Using the 'edit this page" link takes me here: https://wiki.metagame.wtf/admin#/?/docs/playbooks/how-to-coach-eth.md  
That simply redirects to a login page.  
After logging in, I land here: https://wiki.metagame.wtf/admin#/collections/enter-metagame and am unable to find anything on this particular playbook. 
Searching by title returns nothing: https://wiki.metagame.wtf/admin#/collections/wtf-is-metagame/search/How%20to%20Coach%20Eth

**Comment by chair28980** [comment]
@plasmacorral Thank you for the suggestions! I'll get this in asap.

In reference to the navigation and editing bugs you detailed, I'll do some investigation on the proper repo to create the issue in (it's either this repo or TheGame).

**Comment by Baconaetor** [comment]
@chair28980 What's the status on this? Is this issue ready to be closed? 

Also, @plasmacorral I'm not sure if @chair28980 fixed it or not, but I can find this article through the editing portal now.

**Comment by luxumbra** [comment]
@chair28980 I assumed you're flat out with other stuff, so have merged @plasmacorral PR (#305) which closes this out.
