### ISSUE TITLE
Bad sidebars file

### ISSUE THREAD

**Issue by jonathanprozzi** [MetaFam/metagame-wiki#261]
I was about to start working on #253 and got an error while running locally:
`Starting the development server...
Error: Bad sidebars file.
These sidebar document ids do not exist:
- wtf-is-metagame/300-of-metagame`,

This is resolved locally by  adding a `.md` extension to the `the 300-of-metagame` file. I think without the `.md` extension it won't be picked up in the sidebars config, even if the file exists in the directory (without an extension)

**Comment by jonathanprozzi** [comment]
Just saw that this is already being addressed in PR #260  -- will delete my PR.

**Comment by luxumbra** [comment]
These changes are now in master, so closing. Thanks for looking into it @jonathanprozzi 🙏🏻
