### ISSUE TITLE
Wiki: Playbook Links overlap on Sidebar

### ISSUE THREAD

**Issue by tommycomma** [MetaFam/metagame-wiki#334]
When you are on the sidebar and click the pull down menu for Playbooks then choose a playbook,

Such as here https://wiki.metagame.wtf/docs/playbooks/how-to-make-it-without-technical-skills

The playbook's sections overlap as a new sidebar..

Looks like this
![image](https://user-images.githubusercontent.com/93880424/150909854-7a73424b-6d3d-48bc-a91d-a88997bdf1e9.jpeg)

**Comment by luxumbra** [comment]
hey @tommycomma could you include your browser, screen size and operating system when reporting display bugs like this? Thanks. 🙏🏻

**Comment by luxumbra** [comment]
Closing as the issue is the same as in #315
