### ISSUE TITLE
Split calls to action

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#58]
As it currently stands, we have 3 separate buttons on the main wiki page;
"for players", "for guilds" & "for patrons" - BUT! Their buttons all lead to a single page: introduction
https://wiki.metagame.wtf/

I wanted to change that, but looks like all 3 buttons are written as a single "call to action" (or "through here" if my pull request gets merged meantime), and I don't know how to split them into 3 buttons.

Each button should be leading to a different page on the wiki, they're all in there already:
https://wiki.metagame.wtf/docs/handbook/for-players
https://wiki.metagame.wtf/docs/handbook/for-guilds
https://wiki.metagame.wtf/docs/handbook/for-investors

The change is made through here:
https://github.com/MetaFam/metagame-wiki/edit/master/src/pages/index.js

**Comment by krzysu** [comment]
I will do it
