### ISSUE TITLE
Embed SourceCred

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#59]
I added this leaderboard page:
https://wiki.metagame.wtf/docs/roadmap/leaderboard

But I have no idea how to actually integrate our sourcecred page into it..
Is that even possible?
https://metafam.github.io/TheSource/timeline/@metagame/

**Comment by peth-yursick** [comment]
Is this how you do it?
https://github.com/MetaFam/metagame-wiki/pull/61

**Comment by krzysu** [comment]
solved in #61
